name: CodeSign Protect Sign
on: workflow_dispatch
 
env:
  TPP_AUTH_URL: ${{ secrets.TPP_AUTH_URL }}
  TPP_HSM_URL: ${{ secrets.TPP_HSM_URL }}
  TPP_USERNAME: cosignkeyuser
  TPP_PASSWORD: ${{ secrets.TPP_PASSWORD }}
  TPP_PASSWORD: ${{ secrets.TPP_PASSWORD }}
  IMAGE_NAME: dadsvacayshorts/bootcamp-signed
  
   
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sign:
    runs-on: [ self-hosted ]
    steps:
    - name: Log into registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - name: Sign image 
      run: |
        pkcs11config getgrant --force --authurl=${{ env.TPP_AUTH_URL }} --hsmurl=${{ env.TPP_HSM_URL }} --username=${{ env.TPP_USERNAME }} --password=${{ env.TPP_PASSWORD }}
        pkcs11config sync
        URI=`/usr/local/bin/cosign pkcs11-tool list-keys-uris --module-path /opt/venafi/codesign/lib/venafipkcs11.so --pin 1234|grep "URI:" | sed -e 's/URI://g'`
        cosign sign --key $URI --tlog-upload=false --issue-certificate=false {{ env.IMAGE_NAME }}
        pkcs11config revokegrant
