name: Test run v1

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [ self-hosted ]
    steps:
      - name: Show environment v1
        run: env | grep ^GITHUB
      - name: Show ref v1
        run: echo "===============> Version from $GITHUB_REF"
